# iOS-specific configuration

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-fapplication-extension"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-fapplication-extension"]

[env]
IPHONEOS_DEPLOYMENT_TARGET = "14.0"

# Convenient aliases for common tasks
[alias]
# Run xtask commands
xtask = "run --package xtask --"
# Shortcut for building iOS framework
ios = "run --package xtask -- build-ios"
